# Generated by Django 5.0.6 on 2024-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="bio",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="text",
            new_name="quote",
        ),
        migrations.RemoveField(
            model_name="author",
            name="name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="created",
        ),
        migrations.AddField(
            model_name="author",
            name="born_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="born_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="fullname",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
